export const festInfo = {
  title: "Hello World",
  edition: "26-27 Edition",
  date: "13-Aug-2026",
  formattedDate: "Thursday, August 13, 2026",
  timeSpan: "09:30 AM — 04:30 PM",
  logo: "/assets/logo.png",
  supportPhone: "+91 99999 88888",
  supportEmail: "help@helloworldfest.com",
  helpDesk: "Seminar Hall Lobby (1st Floor)",
  copyright: "Copyright © @helloworld2k26"
};

export const events = [
  {
    index: 1,
    id: "inauguration",
    name: "Inauguration",
    startTime: "09:30 AM",
    endTime: "10:00 AM",
    date: "13-Aug-2026",
    type: "program",
    venue: "Rev. Fr. P. Paul Raj Kumar Hall",
    description: "Formal inauguration of Hello World '26-'27 Edition, an inter-collegiate technical competition organised by the PG Department of Computer Applications.",
    rules: [],
  },
  {
    index: 2,
    id: "paper-presentation",
    name: "Paper Presentation",
    startTime: "10:15 AM",
    endTime: "11:30 AM",
    date: "13-Aug-2026",
    type: "event",
    venue: "Rev. Fr. P. Paul Raj Kumar Hall",
    description: "Topic: Artificial Intelligence - Transforming the Future. Time Duration: 05 Minutes (4 Minutes for presentation, 1 Minute for Q&A).",
    rules: [
      "The presentation should contain a minimum of 10 slides and a maximum of 15 slides",
      "Communication must be strictly in English",
      "Email your presentation to helloworld2k26ppt@gmail.com on or before 10-08-2026"
    ],
  },
  {
    index: 3,
    id: "web-development",
    name: "Web Development",
    startTime: "10:30 AM",
    endTime: "11:30 AM",
    date: "13-Aug-2026",
    type: "event",
    venue: "BCA Lab",
    description: "Images, videos and the Topic will be provided on the spot; Design a webpage using HTML, CSS and JavaScript; Time Duration: 1 Hour.",
    rules: [],
  },
  {
    index: 4,
    id: "code-blast",
    name: "Code Blast",
    startTime: "11:30 AM",
    endTime: "12:30 PM",
    date: "13-Aug-2026",
    type: "event",
    venue: "M.Sc. Lab",
    description: "From Output to Logic.",
    rules: [
      "An expected output will be provided on the spot to challenge participants' quick thinking and coding efficiency",
      "Contestants must solve the problem using C / C++ / Java / Python",
      "Evaluation will be based on problem-solving ability, speed, coding skills, and execution time",
      "Time Duration: 1 Hour"
    ],
  },
  {
    index: 5,
    id: "debugging-challenge",
    name: "Debugging Challenge",
    startTime: "02:00 PM",
    endTime: "03:00 PM",
    date: "13-Aug-2026",
    type: "event",
    venue: "M.Sc. Lab",
    description: "Source code will be provided with errors; Only Python Language is allowed; Time Duration: 1 Hour.",
    rules: [],
  },
  {
    index: 6,
    id: "sql-query-challenge",
    name: "SQL Query Challenge",
    startTime: "02:00 PM",
    endTime: "03:30 PM",
    date: "13-Aug-2026",
    type: "event",
    venue: "BCA Lab",
    description: "Participants must use only the Oracle SQL environment provided in the lab; ROUND 1: Debugging the SQL Query (Error Identification Round); ROUND 2: Query Writing Round (Output Generation Round); Time duration: 30 min for each round.",
    rules: [],
  },
  {
    index: 7,
    id: "valedictory",
    name: "Valedictory",
    startTime: "03:45 PM",
    endTime: "04:30 PM",
    date: "13-Aug-2026",
    type: "program",
    venue: "Rev. Fr. P. Paul Raj Kumar Hall",
    description: "Valedictory ceremony and prize distribution.",
    rules: [],
  }
];
