export const festInfo = {
  title: "Hello World",
  edition: "26-27 Edition",
  date: "13-Aug-2026",
  startTime: "08:30",
  endTime: "16:00",
  logo: "/assets/logo.png",
  supportPhone: "+91 99999 88888",
  supportEmail: "help@helloworldfest.com",
  helpDesk: "Seminar Hall Lobby (1st Floor)",
};

export const events = [
  {
    index: 1,
    id: "inauguration",
    name: "Inaugural Ceremony & Prayer",
    startTime: "08:30",
    endTime: "09:00",
    date: "13-Aug-2026",
    type: "program",
    chiefGuest: "Dr. Jane Doe",
    chiefGuestTitle: "Director of AI Research at Google DeepMind",
    venue: "Seminar Hall A (1st Floor)",
    description: "Inaugural welcome address, prayer song, and formal lighting of the lamp by our Guest of Honor.",
    rules: [],
  },
  {
    index: 2,
    id: "web-development",
    name: "Web Development Showcase",
    startTime: "09:00",
    endTime: "10:30",
    date: "13-Aug-2026",
    type: "event",
    coordinator: "Sarah Connor",
    phone: "9876543210",
    venue: "Lab 3 (3rd Floor)",
    description: "Forge the future of the web! Form a team and build a beautiful, responsive web application from scratch. Show off your design and functional coding skills.",
    rules: [
      "Team size: Maximum of 3 members.",
      "All code must be written during the event hours. No pre-coded templates allowed.",
      "Bootstrap, Tailwind CSS, or custom CSS are permitted.",
      "Websites must be hosted publicly (e.g. Vercel, Netlify) and link submitted before the deadline."
    ],
  },
  {
    index: 3,
    id: "competitive-programming",
    name: "Algorithmic Arena",
    startTime: "11:00",
    endTime: "13:00",
    date: "13-Aug-2026",
    type: "event",
    coordinator: "Alan Turing",
    phone: "9876543211",
    venue: "Main Computer Lab (2nd Floor)",
    description: "Put your algorithmic problem-solving speed to the test. Compete individually to solve complex coding challenges under strict time constraints.",
    rules: [
      "Individual participation only.",
      "Supported languages: C++, Java, Python, and Go.",
      "Plagiarism of any form will lead to immediate disqualification.",
      "Rankings are determined by correct submissions first, followed by time-to-solve penalty points."
    ],
  },
  {
    index: 4,
    id: "lunch-break",
    name: "Lunch Break & Networking",
    startTime: "13:00",
    endTime: "13:30",
    date: "13-Aug-2026",
    type: "program",
    venue: "Student Lounge (1st Floor)",
    description: "Take a break, grab lunch, and network with fellow participants and mentors.",
    rules: [],
  },
  {
    index: 5,
    id: "ui-ux-design",
    name: "UI/UX Showdown",
    startTime: "13:30",
    endTime: "15:00",
    date: "13-Aug-2026",
    type: "event",
    coordinator: "Don Norman",
    phone: "9876543212",
    venue: "Design Studio (Ground Floor)",
    description: "Design a premium, user-friendly interface for a real-world problem statement. Focus on smooth user flows, visual systems, and high-fidelity prototype interactions.",
    rules: [
      "Teams of 1 or 2 members.",
      "Allowed tools: Figma, Adobe XD, or Sketch.",
      "Submissions must include a clickable prototype link and 3 presentation slides.",
      "Evaluation is based on visual consistency, user journey clarity, and design guidelines."
    ],
  },
  {
    index: 6,
    id: "tech-quiz",
    name: "Grand Tech Quiz",
    startTime: "15:00",
    endTime: "16:00",
    date: "13-Aug-2026",
    type: "event",
    coordinator: "Ada Lovelace",
    phone: "9876543213",
    venue: "Seminar Hall A (1st Floor)",
    description: "Fast-paced digital trivia quiz. Compete in teams through multiple rapid-fire rounds covering computer history, emerging systems, and logical puzzles.",
    rules: [
      "Teams of exactly 2 members.",
      "Round 1: Digital MCQ test (30 questions in 15 minutes).",
      "Top 6 teams advance to the live buzzer round on stage.",
      "Negative marks apply for incorrect buzzer responses."
    ],
  }
];
